server:
  port: 2333

spring:

  application.name: beginning-mind

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/beginningmind?characterEncoding=UTF-8&useUnicode=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 'x'

  redis:
    redisson:
      file: classpath:redisson-dev.yml

logging:
  level:
    com.spldeolin.beginningmind: DEBUG

thread-pool:
  core-size: 5
  maximum-size: 10
  queue-capacity: 20
  keep-alive-seconds: 60

snow-flake:
  datacenter-id: 1
  machine-id: 1

rsa:
  pulbic-key: 1
  private-key: 2

rpc-url:
  satisficing-identity-app: http://localhost