# 所有“占位符”属性均由profile指定
# core节点下属性映射到CoreProperties类

########################
##                    ##
##       Common       ##
##                    ##
########################

server:
  port: 占位符
  context-path: 占位符

spring:

  profiles.active: ${profile}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 占位符
    username: 占位符
    password: 占位符
    initial-size: 2
    minIdle: 2
    max-active: 30
    validation-query: select 'x'
    test-on-borrow: true

  redis:
    host: 占位符
    port: 占位符
    password: 占位符
    timeout: 2000 #2sec
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0

  jmx:
    enable: false

  rabbitmq:
    host: 占位符
    port: 占位符
    username: 占位符
    password: 占位符
    publisher-confirms: true # 发送确认
    publisher-returns: true # 发送失败退回
    listener:
      simple:
        acknowledge-mode: manual # ACK

logging:
  config: # 未被覆盖时使用默认log4j2.yml

management:
  server:
    port: ${server.port}
    security.enabled: false
  endpoints:
    web:
      base-path: /actuator
      exposure.include: "*"
  endpoint:
    health.show-details: always

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    banner: false
    db-config:
      id-type: INPUT
      logic-delete-value: true
      logic-not-delete-value: false

swagger:
  base-package: com.spldeolin.beginningmind
  base-path: /**
  exclude-path: /error, /actuator/**

core:

  task-executor:
    core-size: 5
    maximum-size: 10
    queue-capacity: 20
    keep-alive-seconds: 60

  snow-flake:
    datacenter-id: 占位符
    machine-id: 占位符

  email:
    server-host: smtp.163.com
    server-port: 25
    addresser-name: # TODO E-Mail
    addresser-email: # TODO E-Mail
    addresser-auth-code: # TODO E-Mail

  oss:
    bucke-name: beginning-mind
    end-point: oss-cn-hangzhou.aliyuncs.com
    access-key-id: # TODO 阿里云OSS
    access-key-secret: # TODO 阿里云OSS
    file-host: image

  enable-security: 占位符

---

########################
##                    ##
##     Devlopment     ##
##                    ##
########################

server:
  port: 2333
  context-path: /

spring:

  profiles: dev

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/beginning_mind?characterEncoding=UTF-8&useUnicode=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root_r0oT

  redis:
    host: 127.0.0.1
    port: 6379
    password: root_r0oT

  rabbitmq:
    host: 192.168.2.2
    port: 5672
    username: admin
    password: admin

core:
  snow-flake:
    datacenter-id: 1
    machine-id: 1
  enable-security: false

---

########################
##                    ##
##        Test        ##
##                    ##
########################

server:
  port: 8080
  context-path: /

spring:

  profiles: test

  datasource:
    url: jdbc:mysql://192.168.2.2:3306/beginning_mind?characterEncoding=UTF-8&useUnicode=true&allowMultiQueries=true
    username: guest
    password: guest

  redis:
    host: 192.168.2.2
    port: 6379
    password: guest

  rabbitmq:
    host: 192.168.2.2
    port: 5672
    username: admin
    password: admin

logging:
  config: classpath:log4j2/log4j2-test.yml

core:
  snow-flake:
    datacenter-id: 1
    machine-id: 1
  enable-security: false

---

########################
##                    ##
##     Production     ##
##                    ##
########################

server:
  port: # TODO 生产环境 端口号
  context-path: /

spring:

  profiles: prod

  datasource:
    url: # TODO 生产环境 MySQL
    username: # TODO 生产环境 MySQL
    password: # TODO 生产环境 MySQL

  redis:
    host: # TODO 生产环境 Redis
    port: # TODO 生产环境 Redis
    password: # TODO 生产环境 Redis

  rabbitmq:
    host: # TODO 生产环境 RabbitMQ
    port: # TODO 生产环境 RabbitMQ
    username: # TODO 生产环境 RabbitMQ
    password: # TODO 生产环境 RabbitMQ

logging:
  config: classpath:log4j2/log4j2-prod.yml

swagger:
  exclude-path: /** # 不显示一切API

core:
  snow-flake:
    datacenter-id: # TODO 生产环境 雪花算法数据中心ID
    machine-id: # TODO 生产环境 雪花算法机器ID
  enable-security: true